# Generated by Django 2.2.17 on 2021-03-30 11:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_auto_20210319_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 11, 14, 55, 147416, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
